# Site settings
title: Qiuge'Blog
logo: img/logo.png
logo1: img/logo1.png
header-img: img/home-bg.jpg
email: zhangbaige@innobuddy.com
description: > # this means to ignore newlines until "baseurl:"
  本博客就是为了整理工作上遇到的问题，以求能够整理一套完成的开发规范
baseurl: "/blog" # the subpath of your site, e.g. /blog/
encoding: utf-8
url: "http://qiuge.me" # the base hostname & protocol for your site
twitter_username: qiuge227
github_username:  qiuge227
weibo_username: 275977447

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
